ARG BIN
ARG VERSION

FROM ghcr.io/fluxcd/notification-controller:${VERSION} as source
FROM registry.access.redhat.com/ubi10/ubi-minimal

COPY --from=source /usr/local/bin/notification-controller /usr/local/bin/notification-controller
# Required Licenses
COPY LICENSE /licenses/

### Required OpenShift Labels
LABEL name="FluxCD notification-controller" \
      maintainer="AppsCode" \
      vendor="AppsCode" \
      release="1" \
      summary="This is the FluxCD notification-controller image" \
      description="This is the FluxCD notification-controller image"

ENTRYPOINT ["/usr/local/bin/notification-controller"]
