ARG BIN
ARG VERSION

FROM ghcr.io/fluxcd/image-automation-controller:${VERSION} as source
FROM registry.access.redhat.com/ubi10/ubi-minimal

COPY --from=source /usr/local/bin/image-automation-controller /usr/local/bin/image-automation-controller
# Required Licenses
COPY LICENSE /licenses/

### Required OpenShift Labels
LABEL name="FluxCD image-automation-controller" \
      maintainer="AppsCode" \
      vendor="AppsCode" \
      release="1" \
      summary="This is the FluxCD image-automation-controller image" \
      description="This is the FluxCD image-automation-controller image"

ENTRYPOINT ["/usr/local/bin/image-automation-controller"]
